### ISSUE TITLE
Data Corruption 

### ISSUE THREAD

**Issue by legel** [simondlevy/PyMaxBotix#1]
First of all, thanks for writing and publishing this!

Quick fix to a bug in data corruption.  Every once in a while this error comes up:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sense/PyMaxBotix/maxbotix/__init__.py", line 35, in _update
    c = self._device.read(1)
  File "/home/sense/.local/lib/python2.7/site-packages/serial/serialposix.py", line 493, in read
    buf = os.read(self.fd, size - len(read))
TypeError: an integer is required

```

My solution is just to add a TypeError exception catch, and break to ignore that reading:
```
# Get byte from sensor
try:
  c = self._device.read(1)
except TypeError:
  break
```

**Comment by simondlevy** [comment]
Thanks, Lance!  If you can do a pull request, I'll be happy to incorporate your fix.
